# Generated by Django 4.2.5 on 2023-09-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_medico', models.TextField(verbose_name='Nota')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=50, verbose_name='Nome do cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=13, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('informacoes_medicas', models.TextField(verbose_name='Informações Médicas')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pacientes')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('pertence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.CharField(max_length=100, verbose_name='Médico')),
                ('nome_paciente', models.CharField(max_length=100, verbose_name='Nome do Paciente')),
                ('codigo', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('observacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.anotacao')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.prontuario')),
                ('tipo_procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo_procedimento', verbose_name='Tipo de Procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=13, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_medicos')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=13, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cargo')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco')),
            ],
        ),
    ]
