# Generated by Django 4.2.5 on 2023-09-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_cargo_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco'),
        ),
    ]
