# Generated by Django 4.2.5 on 2023-09-22 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_funcionario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco'),
        ),
    ]
