# Generated by Django 4.2.5 on 2023-10-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_agendamento_consulta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissão'),
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
    ]
