# Generated by Django 4.2.5 on 2023-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_funcionario_usuario_medico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='CRM'),
        ),
    ]
