# Generated by Django 4.2.5 on 2023-10-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_medico_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_medico', models.TextField(verbose_name='Nota')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horarios_disponiveis', models.JSONField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.medico')),
            ],
        ),
    ]
