# Generated by Django 4.2.5 on 2023-10-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_nota_agendamedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('data_hora', models.DateTimeField()),
                ('tipo_consulta', models.CharField(choices=[('Plano', 'Plano'), ('Particular', 'Particular')], max_length=10)),
                ('retorno', models.BooleanField(choices=[('True', 'Sim'), ('False', 'Não')], default=False)),
                ('valor_consulta', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.especialidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Agendamento_Consulta',
        ),
    ]
