# Generated by Django 4.2.5 on 2023-10-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_dataagenda_remove_agendamedico_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='horario_disponivel',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_inicial',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
