# Generated by Django 4.2.5 on 2023-10-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_remove_horariodisponivel_horario_disponivel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariodisponivel',
            old_name='horario_final',
            new_name='horario_disponivel',
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='horario_inicial',
        ),
    ]
