# Generated by Django 4.2.5 on 2023-10-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_funcionario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamedico',
            old_name='medico',
            new_name='egenda',
        ),
    ]
