# Generated by Django 4.2.5 on 2023-10-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_rename_medico_agendamedico_egenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataagenda',
            old_name='agenda',
            new_name='medico',
        ),
    ]
