# Generated by Django 4.2.5 on 2023-10-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_rename_agenda_dataagenda_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamedico',
            old_name='egenda',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='dataagenda',
            old_name='medico',
            new_name='agenda',
        ),
    ]
