# Generated by Django 4.2.5 on 2023-10-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_rename_egenda_agendamedico_medico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariodisponivel',
            old_name='agenda',
            new_name='data_agenda',
        ),
    ]
