# Generated by Django 4.2.5 on 2023-10-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_rename_agenda_horariodisponivel_data_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.medico')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_atendimento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')])),
                ('horario_inicio_manha', models.TimeField(blank=True, null=True)),
                ('horario_fim_manha', models.TimeField(blank=True, null=True)),
                ('horario_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('horario_fim_tarde', models.TimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.medico')),
            ],
        ),
        migrations.RemoveField(
            model_name='dataagenda',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='data_agenda',
        ),
        migrations.DeleteModel(
            name='AgendaMedico',
        ),
        migrations.DeleteModel(
            name='DataAgenda',
        ),
        migrations.DeleteModel(
            name='HorarioDisponivel',
        ),
    ]
