# Generated by Django 4.2.5 on 2023-10-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_horarioagenda_horarioatendimento_horariomedico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariomedico',
            old_name='horario_fim_manha',
            new_name='horario_final_manha',
        ),
        migrations.RenameField(
            model_name='horariomedico',
            old_name='horario_fim_tarde',
            new_name='horario_final_tarde',
        ),
        migrations.RenameField(
            model_name='horariomedico',
            old_name='horario_inicio_manha',
            new_name='horario_inicial_manha',
        ),
        migrations.RenameField(
            model_name='horariomedico',
            old_name='horario_inicio_tarde',
            new_name='horario_inicial_tarde',
        ),
    ]
