# Generated by Django 4.2.5 on 2023-10-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_rename_horario_fim_manha_horariomedico_horario_final_manha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariomedico',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')]),
        ),
    ]
