# Generated by Django 4.2.5 on 2023-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_remove_horariomedico_medico_agendamedico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatendimento',
            name='horario_atendimento',
            field=models.TimeField(unique=True),
        ),
    ]
