# Generated by Django 4.2.5 on 2023-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_alter_horarioatendimento_horario_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioagenda',
            name='disponivel',
        ),
        migrations.AlterField(
            model_name='horariomedico',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')]),
        ),
    ]
