# Generated by Django 4.2.5 on 2023-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_remove_horarioagenda_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
