# Generated by Django 4.2.5 on 2023-10-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_alter_agendamentoconsulta_valor_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentoconsulta',
            name='codigo',
        ),
    ]
