# Generated by Django 4.2.5 on 2023-10-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_agendamentoconsulta_consulta_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='consulta_realizada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
