# Generated by Django 4.2.5 on 2023-11-10 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_remove_procedimentoagendado_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Consulta', 'Consulta'), ('Procedimento', 'Procedimento')], max_length=12, verbose_name='Tipo de agendamento')),
                ('procedimento', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(null=True)),
                ('horario', models.TimeField(null=True, verbose_name='Horário')),
                ('tipo_pagamento', models.CharField(choices=[('Plano', 'Plano'), ('Particular', 'Particular')], default='Particular', max_length=10, verbose_name='Tipo de pagamento')),
                ('retorno', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('concluido', models.BooleanField(default=False, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente')),
            ],
        ),
        migrations.RenameField(
            model_name='procedimento',
            old_name='valor',
            new_name='valor_procedimento',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.especialidade'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais Sobre o Procedimento'),
        ),
        migrations.DeleteModel(
            name='AgendamentoConsulta',
        ),
    ]
