# Generated by Django 4.2.5 on 2023-11-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_atendimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='especialidade',
            new_name='especialidade_responsavel',
        ),
    ]
