# Generated by Django 4.2.5 on 2023-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0036_rename_especialidade_procedimento_especialidade_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='tipo',
            new_name='tipo_agendamento',
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='descricao',
            field=models.TextField(null=True, verbose_name='Descricão'),
        ),
    ]
