# Generated by Django 4.2.5 on 2023-11-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_rename_tipo_agendamento_tipo_agendamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='procedimento',
            new_name='consulta',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_agendamento',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Procedimento', 'Procedimento')], default='Consulta', max_length=12, verbose_name='Tipo de agendamento'),
        ),
    ]
