# Generated by Django 4.2.5 on 2023-11-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_rename_procedimento_atendimento_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.procedimento'),
        ),
    ]
